### PR TITLE
Added Red-Black Tree (DSA) source code 

### PR DESCRIPTION
**Pull request by prabhash-varma**
Hello, I have added the source code of RED-BLACK tree on Tree Folder . I am participating in hactoberfest2021 ,please merge my pull request.

Thank you

### CODE REVIEW

**Comment by deephunt3r** [comment]
Hey, @prabhash-varma  don't make PR directly . We have to check whether the problem is already there or not . So please raise an issue first and then make PR After assigning you to the solve the issue

**Comment by deephunt3r** [comment]
Hey @prabhash-varma Please Add your file in 
- Trees
   - Red_Black_Trees folder(create new)

**Comment by prabhash-varma** [comment]
Sir, Do I need to create an issue now or I can add my file directly to Tree Folder?

**Comment by deephunt3r** [comment]
Create a folder with name Red_black_Trees in Tree folders and add your file

**Pull request closed without merging**
