### PR TITLE
Insertion Sort

### PR DESCRIPTION
**Pull request by pushpendra-91**
Merge it for Hacktoberfest

### CODE REVIEW

**Review by bvsslgayathri-8679 — APPROVED** [review]
approval done

**Comment by pushpendra-91** [comment]
@deephunt3r why invalid or spam added ?

**Comment by deephunt3r** [comment]
You just pasted the code from gfg

**Comment by deephunt3r** [comment]
@pushpendra-91 we encourage you to make open source contributions even it is small it's a contribution but copy paste doesn't make sense 😃

**Pull request merged**
