### PR TITLE
Added Single Linked list

### PR DESCRIPTION
**Pull request by Dinesh0602**
## Related Issue 

-Formation of complete linked list in C++

Closes: #25 

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.

## Screenshots(optional)

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |

### CODE REVIEW

**Review by bvsslgayathri-8679 — COMMENTED** [review]
not approved

**Comment by tireless-22** [comment]
This code is old c style coding in c++

**Comment by Dinesh0602** [comment]
Okay

**Comment by deephunt3r** [comment]
> Okay

Don't worry you can code in c

**Pull request closed without merging**
