### PR TITLE
Added Kosaraju's Algorithm

### PR DESCRIPTION
**Pull request by imsushant12**
## Related Issue 

#84 

Closes: #84 

### Describe the changes you've made

I have implemented Kosaraju's Algorithm to find strongly connected components in C++.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

I have verified it with sample input-output

### CODE REVIEW

**Review by himabindu-run — COMMENTED** [review]
Plagiarism found.

**Comment by imsushant12** [comment]
> Plagiarism found.

May I know from where?

**Comment by himabindu-run** [comment]
https://gist.github.com/ABHIINAV12/fb8820ac4d6a57c3b18205b7a2aade7c

The syntax is a little different but it is very similar.
The input is also exactly the same.
@imsushant12

**Comment by imsushant12** [comment]
> https://gist.github.com/ABHIINAV12/fb8820ac4d6a57c3b18205b7a2aade7c
> 
> The syntax is a little different but the code is very similar. The input is also exactly the same. @imsushant12

It is similary coded on GFG as well. Algorithms are usally same everywhere.

**Comment by himabindu-run** [comment]
> > https://gist.github.com/ABHIINAV12/fb8820ac4d6a57c3b18205b7a2aade7c
> > The syntax is a little different but the code is very similar. The input is also exactly the same. @imsushant12
> 
> It is similary coded on GFG as well. Algorithms are usally same everywhere. I can give different input.

Hey, that's not the problem 😄  Of course, you can change the input. We are making the review a little stricter and encouraging diverse PRs. We will merge it for sure. No worries.

**Review by deephunt3r — APPROVED** [review]

**Pull request merged**
